[[CeresSolver]]
arch = "aarch64"
git-tree-sha1 = "3f347896fee5c35c533d64f5831238e154d18d30"
os = "macos"

    [[CeresSolver.download]]
    sha256 = "f43613ebcaeb52b673ef565cc80ae21b909eb1d90f0722a0919a02e77fe4d616"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.aarch64-apple-darwin.tar.gz"
[[CeresSolver]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d32dee976b5661039a44124d2653006118c80308"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "5911db44f7d3b340acad4348d16dad85439cc68a97db99a01b204f0c623e4251"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[CeresSolver]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "344c638e41cdfdce77498423c81ad67fcff71e55"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "c1de71c1e336cf6fc3903f1f4bb2929e7b4ca9255a10208b74da2e049106f268"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[CeresSolver]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7613f7da7c9cd4838636433a37d9ca96ac27aff"
libc = "musl"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "145e06e80f0953da4d4c893de7f63a782a1da0eabb4ede0d576ae20a165b9448"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[CeresSolver]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c67681e6a68a93ceac109b555f5263fd468317f"
libc = "musl"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "d375861997894cfcfa926bccd6fe8ac2defc6c01907a5d278492f3ce5b4ecdea"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[CeresSolver]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9119530282f501e626e52cb3191887bf6b50d9b1"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "27e5d680468a21c14f5ddd8bc654d6661235dafb70eb6c3868e392618e2eafa0"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CeresSolver]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b998ec6adcf93ae5dc8528e7c6f5f4e1521207fb"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "03993d45babb5af83f9c5bc12209539daae2ab1da39bf3fbbabb12347f2f4d94"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CeresSolver]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef785b54c80f8353893895d79cfd6089f6e57aca"
libc = "musl"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "9d9af1c891bdfcd4f63692ef247d7b62d1850a304e24c29fd1166fa4d521aad8"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CeresSolver]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e7684dfcaf5262a5ab214428aac497f1386692f"
libc = "musl"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "b54b3d0d0d05541ac7d6ef4c0bc1d497bbcba950af0e27cbadb53a46914023dd"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CeresSolver]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2389823cbd1677ae1f8cd9ab4d432d379e46372b"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "40b4d17a5cbe200f5089e95b97bea7461fb487035b4d2db5502f6bd194e3e80b"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CeresSolver]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ceca397ba54516b2d82fb159677bf5b923f9da42"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "78b35375d36a4a3f72e0e9d761d8fcd7236b5b44867f24443ef173191c75e246"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CeresSolver]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db2f7a699e5b077b36bcce15e24fb500db28dd11"
libc = "musl"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "49dddf6962a73619806c47a8b696b692d80472a9160b1fad6f946477fd7e42a4"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CeresSolver]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55eeeb6e86fe43e19d1836831658495614254caa"
libc = "musl"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "71dd9333a6019fb93af1d4badaa613928c0df11ba20a092d8595f6737f6750c2"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CeresSolver]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff85d84887db792eabecc897a5f42b294643d8b2"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "a6dedcd0e45ab2848a043a9722bc3baf83c5aa79b581dafb5859b32fc2e3612c"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.i686-linux-gnu-cxx03.tar.gz"
[[CeresSolver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a701c7a4e124b9d12c6cc38b306c17a8bf2f21b1"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "8db3a62fc1b42d43f72abff2ba5e4f81a1f8319422d0c1db2d40861906ef7462"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.i686-linux-gnu-cxx11.tar.gz"
[[CeresSolver]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "efb08485d737817d5759771048764f675125becc"
libc = "musl"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "20bb4bf710a27abea229ac66e5235b8d2c0d6b6df60a3c0ac7ece0461bbd9a2b"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.i686-linux-musl-cxx03.tar.gz"
[[CeresSolver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "212b405a316aee2dd3418771571e94cd58651a54"
libc = "musl"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "2b6b646cf01ce8ceb9290db3a596f4568ee39145ba5fb50390a39e65e352cdac"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.i686-linux-musl-cxx11.tar.gz"
[[CeresSolver]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "649f56a3149987a425661d36f761391b77006095"
os = "windows"

    [[CeresSolver.download]]
    sha256 = "5933931fac0c4c903d043bbc6f5ab10df8ddf4eb149f9a5bbf36c4f0da09a7e7"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[CeresSolver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d316f8ddb8f628eb91825097c6989d31da800501"
os = "windows"

    [[CeresSolver.download]]
    sha256 = "9dc9979bc4cff0572d41935dd1972f10a6c2b3382bd7d276e7a7b1c269d6b85a"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[CeresSolver]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9bcaef6bfacb94376d9f9d17d6182dceb05e78c2"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "43c93f59835632f278202f6ae71a5f62a789c924cd5db75ff70f9c2600d90472"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CeresSolver]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd41886fc18c7f2ebeccc166cfc428b2a24fad98"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "57e606f5b67d60875ecfb5272265b1960785da953e4815446a8beeb09226bf85"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CeresSolver]]
arch = "x86_64"
git-tree-sha1 = "80b276c2a54086c8ba5a648c750a377e049b9484"
os = "macos"

    [[CeresSolver.download]]
    sha256 = "fa3b92b27b7c437c36452008327c4579d9209708197a915e10f2b3c0e59d2095"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.x86_64-apple-darwin.tar.gz"
[[CeresSolver]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b507050b6693b436a0cabb311ec10941f4904cb"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "66717adb543ef4cc37cf83bac585800aebb1006bd9bc266ef57b3715263c7ecf"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[CeresSolver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d137110a8d2540ce7c5d544b481ce9aff7a5594a"
libc = "glibc"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "924aff7ea5a629c61146e7cae009bc34d8d104c4f087032dbf8f2a4c2d5a1347"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[CeresSolver]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38b02cd04db910acc60ac903280383cd34b1276f"
libc = "musl"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "fff7a2be825921d981cbc939474e1f9a1f2f1f23133491e924feb752ee477f74"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[CeresSolver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04c8610723747c5c678c04d75037891fba9e88bd"
libc = "musl"
os = "linux"

    [[CeresSolver.download]]
    sha256 = "16241834a3624f47777c3ec9fd7698cb66b4f74b17c7f1f7db2d92214be4c6d9"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[CeresSolver]]
arch = "x86_64"
git-tree-sha1 = "6ba11d2f27e7f31da4f25b8488f224baa89a138f"
os = "freebsd"

    [[CeresSolver.download]]
    sha256 = "8e9ed9cef23f9fd5a6fb1f8c49540346c09269a6472fb4bd8f9dfb285e0209ff"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.x86_64-unknown-freebsd.tar.gz"
[[CeresSolver]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6534230f7a96c5349108b2673c9cb6f1c4c42742"
os = "windows"

    [[CeresSolver.download]]
    sha256 = "8446ce08b060e918429c23984694cb6aa61d86a4f85a62c139d2b751e269c46a"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[CeresSolver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7789431efd8fd1806984f8e4113a18721bc20dcd"
os = "windows"

    [[CeresSolver.download]]
    sha256 = "7c0c93a5d5bd918199173f2b5d605a25b16165925f160deba996111e0e1eb4e1"
    url = "https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases/download/CeresSolver-v2.1.0+0/CeresSolver.v2.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
