# Autogenerated wrapper script for CeresSolver_jll for x86_64-w64-mingw32-cxx03
export libceres

using glog_jll
using METIS_jll
using OpenBLAS32_jll
using SuiteSparse_jll
JLLWrappers.@generate_wrapper_header("CeresSolver")
JLLWrappers.@declare_library_product(libceres, "libceres.dll")
function __init__()
    JLLWrappers.@generate_init_header(glog_jll, METIS_jll, OpenBLAS32_jll, SuiteSparse_jll)
    JLLWrappers.@init_library_product(
        libceres,
        "bin\\libceres.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
